---
title: "About Me"
format: html
---

I was trained to be a lawyer in college. When I interned in an international investment team at a top law firm providing legal support for cross-border and IPO businesses, I realized that drafting contracts and negotiating deals were not where my passion lay. After finishing my Master of Laws in International Economic Law at Beijing Normal University, I earned an Erasmus Mundus scholarship to study at University College Dublin. During my time in Ireland, I studied charity law with Professor [Oonagh Breen](https://people.ucd.ie/oonagh.breen). That experience opened the door to the nonprofit world and public policy, and I decided to work in a nonprofit think tank rather than practice law.  

Working closely with nonprofits and policymakers solidified my commitment to serve the collective good. My work provided me the opportunity to collaborate with major international governmental and philanthropic organizations such as the United Nations, the Asian Development Bank, the Gates Foundation, and the Ford Foundation, while also conducting fieldwork and interviewing over 70 grassroots NGOs across China between 2013 and 2016. That was when I was truly amazed by the diversity of the sector and the breadth of lives I could touch through my work. It was also deeply fulfilling to help leverage systematic change by providing policy advice to the National People’s Congress and local policymakers. My rich practical experience continues to fuel my motivation for conducting research in public and nonprofit management.  


## Education

- **Georgia State University (Andrew Young School)**<br>
  Ph.D. in Public Policy, 2026 (expected)  

  * Dissertation: *Nonprofit Commercialization: Three Essays on Its Implications for Social Mission, Access Disparities, and Public Perceptions*  
  * Committee: Janelle Kerlin (Chair), Jason Coupet, Lewis Faulk, Chao Guo, Andrew Heiss  

- **University College Dublin**,<br>
Master of Laws (LLM) in Commercial Law, 2012  

- **Beijing Normal University**  <br>
  Master of Laws (LLM) in International Economic Law, 2011  <br>
  Bachelor of Laws and English Literature (Outstanding Graduate), 2009  

## Work Experience

- **Emory University Vulnerability and the Human Condition Initiative**  <br>
  Visiting Scholar, 08/2018 – 01/2020 
  
  * Applied vulnerability theory framework to study interdependence of government and NGOs in China.  
  * Audited courses in U.S. income tax law and vulnerability theory, connecting legal and public policy perspectives.  
  
- **China Philanthropy Research Institute**  <br>
  Deputy Director of the Center for Charity Law, 03/2015 – 12/2019  
  
  *	Provided research and consultancy support for the National People's Congress and the Ministry of Civil Affairs and local policy makers in Beijing and Yunnan. 
  *	Conducted research projects funded by both domestic and international organizations such as the Ford Foundation, the Gates Foundation and the Asia Foundation.
  *	Interviewed grassroots NGOs and local regulators across the country regarding the management and regulation of nonprofit organizations.
  *	Led nonprofit education endeavors, developed practical guidance, toolkits, social media platforms and MOOCs on China’s Charity Law and Overseas NGO Law.

- **China Law Development Consultants**  <br>
  Research Assistant to President, 03/2013 – 03/2015 
  
  * Conducted comparative research on nonprofit policies and laws in the U.S., UK, Australia, Germany, and Japan.  
  * Drafted bilingual reports on the state of Chinese NPOs and proposed reforms for the National Development and Reform Commission.  
  * Conducted nationwide field research and stakeholder interviews (NGOs, scholars, officials).  
  * Contributed to an Asian Development Bank project on reforming China’s nonprofit regulatory system.  

## Consultancy and Data Projects

- **National Rapporteur (China)** for the International Academy of Comparative Law project *The Social Enterprise: A New Form of the Business Enterprise?*, 2022–2023  

- **Participating Team Member**, *Causal Inference for Social Impact Lab Data Challenge*, Center for Advanced Study in the Behavioral Sciences (CASBS), Stanford University, 2022  

- **Consulting expert and drafter**, *Tax Policy to Promote the Sustainable Development of the Charitable Sector in China*, Shanghai Academy of Contemporary Philanthropy Research Center, 2021  

- **Consulting expert**, *Regulation on the Promotion of Philanthropy in Yunnan Province*, Yunnan Civil Affairs Bureau, 2018–2019  

- **Project leader**, *Several Provisions on the Promotion of Philanthropy in Beijing*, Beijing Civil Affairs Bureau, 2017–2018  

- **Team member**, *Expert Draft of the Charity Law and Implementing Policies*, for the National People’s Congress and Ministry of Civil Affairs, 2015–2017  

- **Team member and report drafter**, *Management System and Legislative Mechanism for Nonprofit Organizations* (TA 7855-PRC), Asian Development Bank/NDRC, 2013–2016  

## Qualifications and Skills

- **Programming and research:** R, Stata, Stan, Quarto, Python (basic), Qualtrics, Sawtooth Software 

- **Professional qualifications:** Licensed Lawyer in China 

- **Languages:** Mandarin (native), English (proficient), French (basic)  

## Contact

I can be reached at [mye2@gsu.edu](mailto:mye2@gsu.edu)  
