---
title: "Publications"
format: html
---

## Journal Articles

- **Ye, M.**, Lu, J., & Dong, Q. (2026). Why Do Nonprofits Invest? Exploring Financial and Political Drivers in Chinese Foundations. [*Nonprofit and Voluntary Sector Quarterly*](https://doi.org/10.1177/08997640261477718). Published online 2026:9-1.

- Hall, K., Kerlin, J. A., & **Ye, M.** (2026). Government versus social enterprise: Comparing the quality of government-run and social enterprise spin-out organizations in English health and social care. [*Journal of Social Policy*](https://www.cambridge.org/core/journals/journal-of-social-policy/article/government-versus-social-enterprise-comparing-the-quality-of-governmentrun-and-social-enterprise-spinout-organisations-in-english-health-and-social-care/EFFBE43A5B9B42D827DB6B50A015FC0F#article). Published online 2026:1-19.

- Kerlin, J. A., **Ye, M.**, & Hall, K. (2026). Do Social Enterprises Fulfill Their Social Mission? Comparing Quality Across Ownership Models in Social Care. [*Public Performance & Management Review*](https://doi.org/10.1080/15309576.2025.2593642). 49(3), 755–781. (**Co-first author with Kerlin**).

- Kerlin, J. A., **Ye, M.**, & Chen, W. (2023). A tax credit proposal for profit moderation and social mission maximization in long-term residential care businesses. [*Nonprofit Policy Forum*](https://www.degruyterbrill.com/document/doi/10.1515/npf-2022-0014/html), 14(1), 77–97.

- Kerlin, J. A., **Ye, M.**, & Hall, K. (2023). Do social enterprises fulfill their social promise? Quality of social care CICs and other legal forms. [*Academy of Management Proceedings*](https://journals.aom.org/doi/pdf/10.5465/AMPROC.2023.155bp?download=true), 2023(1), 15284. (**2023 AOM PNP Best Conference Paper**).

- **Ye, M.** (2021). Building an enabling legal environment: Laws and policies on social enterprises in China. [*Journal of Asian Public Policy*](https://www.tandfonline.com/doi/abs/10.1080/17516234.2020.1824263), 14(2), 182–199.

- Kerlin, J. A., & **Ye, M.**. Social enterprise in Asia: a new legal form: by Ernest Lim, Cambridge, Cambridge University Press, 2023, 350 pp., USD110.00 (hardback), ISBN 978-1-108-83815-3. [*Asia Pacific Law Review.*](https://doi.org/10.1080/10192557.2025.2556089), 34(1), 241–245. (Book Review).

- Lu, E., Ma, L., **Ye, M.**, Shi, Y., Chen, G., Hawes, D., … & Wang, C. (2025). Reimagining the future of IJPA: A vision for 2025 and beyond. [*International Journal of Public Administration*](https://doi.org/10.1080/01900692.2025.2501642), 48(7), 407–410. (Editorial).

## Book Chapters

- **Ye, M.** (2026). [Social enterprises](https://www.taylorfrancis.com/chapters/edit/10.4324/9781003616542-17/social-enterprises-meng-ye). In Q. Dong & J. Lu (Eds.), *Nonprofit organization management in China* (pp. 350–382). Routledge.

- **Ye, M.** (2023). [Social enterprise in China](https://www.researchgate.net/profile/Meng-Ye-13/publication/377806659_SOCIAL_ENTERPRISE_IN_CHINA/links/65b925161e1ec12eff64323c/SOCIAL-ENTERPRISE-IN-CHINA.pdf). In D. Brakman Reiser, S. A. Dean, & G. Lideikyte Huber (Eds.), *Social enterprise law: A multijurisdictional comparative review* (1st ed., pp. 153–180). Larcier‑Intersentia.

- Kerlin, J. A., & **Ye, M.** (2023). [Commercialism](https://www.elgaronline.com/display/book/9781800880092/ch35.xml). In K. F. Kearns & W. Wang (Eds.), *Elgar Encyclopedia of Nonprofit Management, Leadership and Governance* (pp. 105–109). Edward Elgar Publishing.

- **Ye, M.** (editing). Unrelated Business Income Tax (UBIT). In *Encyclopedia of Social Enterprise*. Edward Elgar Publishing. 


## Manuscripts R&R or Under Review

- **Ye, M.** (R & R). Nonprofit commercialization and its implications for social service performance and accessibility: Comparing mission-related and unrelated business income. *Nonprofit Management & Leadership*.

- Sun, J., Shi, Y., & **Ye, M.** (R & R). Unlocking the impact of Charity Law on commercialization of charitable organizations: Evidence from a quasi-experiment design. *Nonprofit Policy Forum*.

- Ke, L., & **Ye, M.** (under review). Does rising tourism lift all boats? Tourism demand shocks and arts nonprofit commercial revenues. *Journal of Urban Affairs*.


## Work in Progress

- **Ye, M.**, & Heiss, A. (preparing for submission). Enforcing boundaries: China’s Overseas NGO Law and operational constraints for global civil society.

- **Ye, M.** (preparing for submission). Nonprofit commercialization in England’s health and social care: Impact on quality rating and the access disparity. (Selected for the **2025 ARNOVA Doctoral Seminar**).

- **Ye, M.** (preparing for submission). How do individual donors respond to nonprofit commercialization and related context and framing: A conjoint survey experiment study. (Selected for the **2026 ARNOVA Emerging Scholars Roundtable**).

- Heiss, A., & **Ye, M.** (preparing for submission). Clarifying correlation and causation: A guide to modern quantitative causal inference in nonprofit studies.

- Ke, L., & **Ye, M.** (writing). Can commercialization improve nonprofit financial health? Evidence from the art industry.

- Heiss, A., & **Ye, M.** (writing). How does reduced reporting burden in 990-EZ impact nonprofits’ financial health?