---
title: "Academic Presentations"
format: html
---

## Conferences

- “Nonprofit Commercialization in England’s Health and Social Care: Impact on Quality Rating and the Access Disparity”, ASPA Annual Conference, Washington D. C., April 2025.

- “Nonprofit Commercialization in England’s Social Care Sector: Impact on Quality Rating and the Mediating Effects of Community Deprivation Level”, ARNOVA Annual Conference, Washington D. C., November 2024.

- “Does Ownership Affect Quality in Health and Social Care Provision? Comparing Government-Run Services with Devolved (Spin-out) and Privately Founded Social Enterprises”, with Janelle Kerlin, Georgia State University and Kelly Hall, University of Birmingham, Public Management Research Conference (PMRC), Seattle, WA, June 2024.

- “Joint Private Provision of Social Good: A Mixed-Method Examination of Nonprofit-Business Collaboration from Multiple Streams”, PMRC, Seattle, WA, June 2024.

- “Nonprofit Commercialization: Examining Mission-Related and Unrelated Business Income and Social Performance Outcomes for Arts Organizations”, APPAM Fall Conference, Atlanta, GA, November 2023.

- “Joint Private Provision of Social Good: A Mixed-Method Examination of Nonprofit-Business Collaboration from Multiple Streams”, ARNOVA Annual Conference, Orlando, FL, November 2023.

- “The devolution and marketization of social care through social enterprise: Does workforce mediate service quality?”, with Janelle Kerlin, Georgia State University, ARNOVA Annual Conference, Orlando, FL, November 2023.

- “A New and Unique Charity Legal Vehicle? Empirical-Based Analysis of Charitable Trusts Under China’s Charity-Law”, ARNOVA Annual Conference, Orlando, FL, November 2023.

- “Operational Flexibility, International Civil Society, and China’s Overseas NGO Law”, with Andrew Heiss, Georgia State University, ARNOVA Annual Conference, Orlando, FL, November 2023.

- “Motivations of Nonprofit Cross-Sector Collaboration: A Mixed-Method Study”, SECoPA, Atlanta, GA, September 2023.

- “Do Social Enterprises Fulfill their Social Promise? Comparing Social Care CICs with other Legal Forms”, AOM Annual Meeting, Boston, MA, August 2023.

- “The Implementation of China’s Overseas NGO Law and the Operating Space for International Civil Society”, with Andrew Heiss, Georgia State University, MPSA Annual Conference, Chicago, IL, April 2023.

- “Nonprofit Commercialization: Examining Mission-Related and Unrelated Earned Income's Impact on DEI and Performance Outcomes”, ASPA Annual Conference, Virtually, March 2023.

- “Do Social Enterprises Fulfill their Social Promise? Comparing Social Care CICs with other Legal Forms”, with Janelle Kerlin, Georgia State University, ASPA Annual Conference, Virtually, March 2023.

- “Nonprofit Commercialization: Examining Mission-Related and Unrelated Business Income and Social Performance Outcomes for Arts Organizations”, ARNOVA Annual Conference, Raleigh, NC, November 2022.

- “Do Social Enterprises Fulfill their Social Promise? Comparing Social Care CICs with other Legal Forms”, with Janelle Kerlin, Georgia State University, ARNOVA Annual Conference, Raleigh, NC, November 2022.

- “Getting Causation Right: A Guide to Observational Causal Inference in Nonprofit Studies”, West Coast Nonprofit Data Conference, Austin, TX, April 2022.

- “Analyzing Charities’ Cross-Sector Collaborations in Chinese Charitable Trust Relationships”, ASPA Annual Conference, Jacksonville, FL, March 2022.

- “Competition or Collaboration? Analyzing charities’ roles in charitable trust relationships after the Enactment of China’s Charity Law”, ARNOVA Annual Conference, Atlanta, GA, November 2021.

- “Exploring a Policy Mechanism for For-Profit Moderation in Social Care Businesses”, with Janelle Kerlin, Georgia State University, ARNOVA Annual Conference, Atlanta, GA, November 2021.

- “Effects of the Implementation of China’s Overseas NGO Law and Its Roles in Regulating Overseas NGOs’ Early Responses to COVID 19 in China”, ISTR Annual Meeting, Virtually, July 2021.

- “The Implementation of China’s Overseas NGO Law and Its Regulatory Roles in Early Responses to COVID-19”, ARNOVA-ASIA Conference, Virtually, July 2021.

- “Isomorphic Process or Not? An Analysis of Social Enterprise Accreditation Policies in China”, Voluntary Action Annual Conference, Virtually, November 2020.

## Seminars and Invited Talks

- “Enforcing Boundaries: China’s Overseas NGO Law and Operational Constraints for Global Civil Society”, Pittsburg University China Governance Series, Virtually, September 17, 2024.

- Plenary Session of “Navigating Trust and Scale in Global Social Enterprise Law”, Annual Conference on Legal Issues in Social Entrepreneurship and Impact Investing, NYU, June 5, 2024.

- “Rules on the Use of Charitable Trust Assets in the U.S.”, Seminar on Charity Trusts of the China Charity Alliance, presented virtually, December 1, 2023.

- “Motivations of Cross-Sector Collaboration: A Mixed Method Study”, Studies on the Chinese Nonprofit and Voluntary Sector Webinar Series, Virtually, June 28, 2023.

- “Empirical-based Comparison of Charitable Trusts in China and the U.S.”, Beijing Normal University School of Social Management Nonprofit Webinar, Virtually, December 28, 2022.

- “Nonprofit Commercialization and Social Outcomes including DEI in Arts Organizations”, AOM PNP Doctoral Consortium, Virtually, August 6, 2022.

- "Building an Enabling Legal Environment: Laws and Policies on Social Enterprise in China”, Social Entrepreneurship in Context webinar, Centre for Social Policy and Social Entrepreneurship, Virtually, January 2021.
