---
title: "Courses Taught"
format: html
---

## Instructor on Record
- **PMAP 3210: Introduction to Nonprofits**  
  Instructor, Summer 2023 (online, synchronous)

- **PMAP 3231: Nonprofit Leadership and Management**  
  Instructor, Fall 2024 (in person)

## Guest Lectures
- **PMAP 3210: Introduction to Nonprofits**  
  Guest lecture on “Financial Management,” Spring 2023 (in person)

- **PHPB 9310: Public Health Finance and Management**  
  Guest lecture on “Nonprofit Finance,” Spring 2025 (in person)

- **PSCI 491: Chinese Politics & Policy** – Montana State University  
  Guest lecture on “Nonprofit Management and Policy in China,” Spring 2025 (hybrid synchronous)

## Course Development
- **PMAP 8511: Big Data for Public Good**  
  Designed and built the course website with Quarto as part of GSU’s big data initiative. The site was adopted as a template/master course on GitHub (<https://aysps.github.io/bigdata4publicgood/>).

## Teaching Assistant and Facilitator
- **PMAP Data Visualization Micro-Credential Workshop**  
  Sessions I & II, February & April 2024 (in person)

- **APPAM Policy Camp at Georgia State University**  
  Group facilitator and panelist, March 2023 (in person)
